name: Github Actions 

on: [pull_request]

jobs: 
  tests: 
    runs-on: ubentu-latest
    strategy: 
      matrix: 
        node-version: [18.x, 20.x, 22.x]

    steps: 
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
      - name: npm install 
        run: npm ci
      - uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start


